import type { Metadata } from 'next';
import './globals.css';
import { colors } from '@/design-tokens';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify';
import { QueryProvider, NextUiProvider } from './_provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body
        style={{
          backgroundColor: colors.bg,
          position: 'relative'
        }}
      >
        <QueryProvider>
          <NextUiProvider>{children}</NextUiProvider>
        </QueryProvider>
        <ToastContainer />
      </body>
    </html>
  );
}
