import localFont from '@next/font/local';
import type { Metadata } from 'next';
import '../globals.css';
import { colors } from '@/design-tokens';
import { Footer } from '@/entities';
import { Nav } from '@/entities/Nav';
import { NextUiProvider, QueryProvider } from '../_provider';
import { layout } from './style.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <div
      style={{
        backgroundColor: colors.bg,
        position: 'relative',
        minHeight: 'calc(100vh - 140.4px)'
      }}
    >
      <Nav />
      <main className={layout}>{children}</main>
      <Footer />
    </div>
  );
}
